services:
  backend-python:
    build: ./backend-python
    container_name: backend-python
    env_file:
      - ./backend-python/.env
    ports:
      - "8000:8000"
    restart: unless-stopped

  backend-java:
    build:
      context: ./backend-java
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend-react
    container_name: frontend-react
    ports:
      - "3000:80"
    restart: unless-stopped