version : "3.9"
services:
  backend-python:
    build: ./backend-python
    container_name: backend-python
    ports:
      - "8000:8000"
    restart: unless-stopped

  backend-java:
    build: ./websem
    container_name: backend-java
    ports:
      - "8080:8080"
    restart: unless-stopped
